language: r
sudo: required # for binary packages

# apt_packages does not work here
addons:
  apt:
    packages:
      - libarpack2-dev

r_binary_packages:
 - tidyverse
 - igraph

cache:
 - packages
 - directories:
    - seq/cache

before_script:
 - make deps
 - make -C stats nmf_mu.so

script: make test
