language: r

addons:
  apt:
    packages:
      - libarpack2-dev

#apt_packages:
# - liblapack-dev # nmf
# - libarpack2-dev # nmf

cache: packages

r_github_packages: klmr/modules

install:
 - make deps
 - make -C stats nmf_mu.so

script: make test
