language: r

# apt_packages does not work here
addons:
  apt:
    packages:
      - libarpack2-dev

cache:
 - packages
 - directories:
    - seq/cache

before_script:
 - make deps
 - make -C stats nmf_mu.so

script: make test
