language: r

# apt_packages does not work here
addons:
  apt:
    packages:
      - libarpack2-dev

cache:
 - packages
 - directories:
    - process/idmap/cache

# does not work
#r_packages:
#r_binary_packages:
# - devtools
# - rmarkdown

r_github_packages: klmr/modules

install:
 - R -e "install.packages(c('devtools','rmarkdown'))"
 - make deps
# - R -e "install.packages('devtools')" \
#     -e "devtools::install_github('klmr/modules',ref='master')"
 - make -C stats nmf_mu.so

script: make test
