language: r
r: bioc-release
sudo: required # for binary packages

# apt_packages does not work here
addons:
  apt:
    packages:
      - libarpack2-dev
      - libudunits2-dev

r_binary_packages:
 - tidyverse
 - igraph
 - devtools
 - rhdf5
 - GenomicRanges
 - matrixStats

cache:
 - packages
 - directories:
    - seq/cache

before_script:
 - make deps
 - make -C stats nmf_mu.so

script: make test
