language: r

# apt_packages does not work here
addons:
  apt:
    packages:
      - libarpack2-dev

cache:
 - packages
 - directories:
    - process/idmap/cache

r_github_packages: klmr/modules

install:
 - make deps
 - R -e "install.packages('devtools')" \
     -e "devtools::install_github('klmr/modules',ref='mschubert-patch-1')"
 - make -C stats nmf_mu.so

script: make test
