language: r
sudo: required # for binary packages

# apt_packages does not work here
addons:
  apt:
    packages:
      - libarpack2-dev

cache:
 - packages
 - directories:
    - seq/cache

r_binary_packages:
 - tidyverse

#r_github_packages: klmr/modules # this does not work either

# modules should work from DESCRIPTION remote, but doesn't
install:
 - make deps
 - Rscript -e "devtools::install_github('klmr/modules')"
 - make -C stats nmf_mu.so

script: make test
