language: r

# apt_packages does not work here
addons:
  apt:
    packages:
      - libarpack2-dev

cache:
 - packages
 - directories:
    - seq/cache

# modules should work from DESCRIPTION remote, but doesn't
install:
 - make deps
 - Rscript -e "devtools::install_github('klmr/modules')"
 - make -C stats nmf_mu.so

script: make test
