language: r

# apt_packages does not work here
addons:
  apt:
    packages:
      - libarpack2-dev

cache:
 - packages
 - directories:
    - process/idmap/gene_table.RData
    - process/idmap/probeset_table.RData

r_github_packages: klmr/modules

install:
 - R -e "devtools::install_github('klmr/modules')"
 - make deps # installs packages
 - make -C stats nmf_mu.so

script: make test
